name: unit-tests
on: [push, pull_request]
jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim:
          - nightly
          - v8.2.0000
          - v8.1.0000
          - v8.0.0000
          - v7.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim }}
      - name: Run Tests
        run: |
          uname -a
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          ./run_tests.sh
  neovim-linux:
    name: neovim-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: stable
          neovim: true
      - name: Run Tests
        run: |
          uname -a
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          ./run_tests.sh
